# Site settings
title: TNTB IMPRO
# tagline: A nancy
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/TNTB" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

include:
  - .htaccess
  - _pages

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Pagination
# Outputting
permalink: pretty
paginate: 4
paginate_path: "/blog/page:num/"

port: 8000



# Directories
collections_dir: collections
layouts_dir: _jekyll/_layouts
includes_dir: _jekyll/_includes

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:  
  posts:
    output: true
    permalink: /:collection/:path


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false