---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: collections/_posts
  label: Post 2
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: jekyll-pages
  label: Home
  create: all
- type: directory
  path: collections/_spectacles
  label: Spectacles
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Post
  create: all
  new_doc_ext: md
- type: directory
  path: _pages
  label: Sections
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
